menu:
#- {name: 'About',   url: 'about.html'}
#- {name: 'Writing', url: 'writing.html'}
#- {name: 'Contact', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github',     link: 'https://www.github.com/jsegurabuisan'}
- {icon: 'twitter',    link: 'https://twitter.com/jsegura_b'}
- {icon: 'envelope',    link: 'mailto:juan.segura@cemfi.edu.es'}
